### ISSUE TITLE
Flathub general gripe

### ISSUE THREAD

**Issue by barthalion** [flathub/io.github.dosbox-staging#2]
Hi @dreamer,

@joshua-stone pointed me to your comment that you are not exactly happy about Flathub workflow(s) – which is exactly the feedback I'm looking for because the ideal outcome would be making developers happy with Flathub so they can actually focus on their projects.

> Now enter Flatpak… users complain it's not on Flathub yet. They throw flatpak scripts at me, but nobody wants to actually take responsibility of packaging it (happened to me 2? 3? times already? writing yml file is easy - maintaining it is the tedious part). And hey, they won - yesterday I rewrote scripts from scratch and submitted them. So now it's as bad as on Windows and macOS. Worse, even - because with Windows, macOS, and Linux tarballs I can automate everything, but not with FlatHub (because metainfo.xml is broken by design). And I am not going to host my own flatpak repo, that's for sure.

Could you expand on what would you like to be automated? I imagine there's not much I can do about metainfo (it's enough to say I'm not its fan either) but please throw everything at me and I may turn it into something actionable.

**Comment by joshua-stone** [comment]
Adding onto this -- there's some flexibility in how you can decrease maintenance burden. The Obsidian flatpak for example has its most frequently-updated sources placed in a separate file:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/sources.json

This file is then updated with a script:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/update-sources.py

Which in turn is hooked into Github Actions:

https://github.com/flathub/md.obsidian.Obsidian/blob/master/.github/workflows/auto-update.yml

The end result is that builds can be updated without human involvement. This isn't a silver bullet, but it at least takes care of the bulk of work that involves version bumping.

**Comment by Eonfge** [comment]
Sorry for digging this up right now... but is this still relevant? We nowadays have the flathub bot that helps a great deal in applying updates, so perhaps it's time to just close this issue or move the discussion elsewhere.

**Comment by rderooy** [comment]
I'm fine with closing this.
