### ISSUE TITLE
Update website reported version from 0.77 to 0.78.1

### ISSUE THREAD

**Issue by kcgen** [flathub/io.github.dosbox-staging#7]
The flatpak contains 0.78.1 but flatpak's website shows 0.77:

![2022-02-07_08-23](https://user-images.githubusercontent.com/1557255/152829147-ca47be9f-4afa-42ab-82b7-6fc9b06ae761.png)

**Comment by kcgen** [comment]
(closing - addressed as a subtopic in https://github.com/flathub/io.github.dosbox-staging/pull/5)

**Comment by hfiguiere** [comment]
this could be addressed here by patching the metainfo as needed.

**Comment by Eonfge** [comment]
https://github.com/flathub/io.github.dosbox-staging/pull/8

**Comment by kcgen** [comment]
Thanks for the fix @Eonfge and for the heads up @grounded0 :+1:
